### ISSUE TITLE
Error: Cannot read property 'getConstant' of undefined in polynomial definition

### ISSUE THREAD

**Issue by RocketingRacer** [numbas/numbas-extension-polynomials#6]
Exams being reviewed or polynomials defined using strings throw the error:  Cannot read property 'getConstant' of undefined in polynomial definition.

Step to reproduce:
Error 1:
Create a variable with value: polynomial("x^2")
Error 2:
Create a variable with a random variable
Create a second variable with polynomial(x,[0,first_var])
Add question to exam.
Load the exam using the LTI provider.  Take the test as a student, then exit and attempt to review the exam.  Throws error.

**Comment by christianp** [comment]
Thanks for reporting this. I think it's a side-effect of some changes in Numbas v6. I've made a change, and it looks like this now works.
